


## Use postgres/example user/password credentials
#version: '3.1'
#
#services:
#  db:
#    image: postgis/postgis
#    container_name: postgres_db
#    volumes:
#      - ./data:/var/lib/postgresql/data
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#
#
#  redis:
#    image: redis
#    container_name: redis
#    restart: always
#    ports:
#      - 6379:6379
#    volumes:
#      - cache:/data
#
#  adminer:
#    container_name: adminer
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#
#volumes:
#  minio_data:
#  cache:
#    driver: local
